global:
  scrape_interval:     30s
  evaluation_interval: 30s

rule_files:
  # - "no rules yet.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    # If prometheus-node-exporter is installed, grab stats about the local machine by default.
    static_configs:
      - targets: ['localhost:9100']
